In [2]:
import numpy as np
import pandas as pd

### Задание 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [4]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [6]:
a1 = a.reshape(6,2)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a2 = a.reshape(2,6)
a2

In [8]:
a3 = a.reshape(3,4)
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a4 = a.reshape(4,3)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
a5 = a.reshape(12,1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Задание 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [13]:
a6 = a.reshape(6, -1)
a6

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [14]:
a7 = a.reshape(2, -1)
a7

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [15]:
a8 = a.reshape(-1, 1)
a8

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [16]:
a9 = a.reshape(-1, 3)
a9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
a10 = a.reshape(-1, 4)
a10

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Задание 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [18]:
a8
#двумерный массив из 1 столбца и 12 строк. Одномерным его можно вопринимать только в контексте работы только с одномерными столбцами, храня их как одномерные строки

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### Задание 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [21]:
a11 = np.random.randn(3, 4)
a11

array([[-0.0170713 , -0.35705888, -2.50354783, -0.61731541],
       [ 0.21542471, -0.50820895,  0.93350612,  0.04690762],
       [ 0.0360404 , -0.6453406 , -1.54601663,  0.47832855]])

In [23]:
a11.size

12

In [24]:
a12 = a11.flatten()
a12

array([-0.0170713 , -0.35705888, -2.50354783, -0.61731541,  0.21542471,
       -0.50820895,  0.93350612,  0.04690762,  0.0360404 , -0.6453406 ,
       -1.54601663,  0.47832855])

In [25]:
a12.size

12

### Задание 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [28]:
a13 = np.arange(20, 0, -2)
a13

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [29]:
b = a13.reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [ ]:
#отличие в том, что он двумерный

### Задание 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [5]:
a14 = np.zeros((2, 2))
b2 = np.ones((3, 2))
c = np.vstack((a14, b2))

print(c)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### Задание 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [15]:
a15 = np.arange(0,13)
#получить такую матрицу можно только из части массива a15[0:12]
print(a15)
A = a15[0:12].reshape(4,3)
print(A)
At = A.T
print(At)
B = A.dot(At)
print(B)
print(np.linalg.det(B))
#определитель равен нулю, посчитать обратную матрицу невозможно

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
0.0


### Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [18]:
np.random.seed(42) 
np.random.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

### Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [27]:
C = np.random.uniform(0, 16, 16)
print(C)

[ 1.41588003  3.1357258   0.72363662  5.20528529  6.21883664  4.34158451
 13.25980015  5.70805323  4.49495215  8.68313733  2.2547876  12.83515169
  1.1928103  15.79019099 12.35591631  3.1794509 ]


### Задание 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [30]:
C = C.reshape(4,4)
D = B + C*10
print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))
D_inv = np.linalg.inv(D)
print(np.linalg.inv(D))

38605954.153053254
4
[[ 0.12125257  0.01575079 -0.03500378 -0.00329153]
 [ 0.08534253 -0.00107918 -0.02738747  0.00701433]
 [-0.0398521   0.00285017  0.00745791  0.00090164]
 [-0.04745793 -0.00403313  0.02007488 -0.00335921]]


### Задание 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [35]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 1.],
       [0., 0., 1., 0.]])

In [ ]:
E = np.where(D_inv == 0, C, B)